### ISSUE TITLE
automatic translation

### ISSUE THREAD

**Issue by Ukkoo** [dotnet/docs-desktop.de-de#2]
I don't know if anyone cares, but the automatic translation of this basic article into German is so bad that essential contents are not or hardly understandable.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c24b9337-46ae-8e6e-587e-2f04399e7755
* Version Independent ID: 52706dd8-5cb8-0d99-fe55-42c404035670
* Content: [Übersicht über die Bildverarbeitung - WPF .NET Framework](https://docs.microsoft.com/de-de/dotnet/desktop/wpf/graphics-multimedia/imaging-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/graphics-multimedia/imaging-overview.md](https://github.com/dotnet/docs-desktop.de-de/blob/live/dotnet-desktop-guide/framework/wpf/graphics-multimedia/imaging-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@Ukkoo thank you for reporting this. I'll ping the localization team. @JasonCard

**Comment by JasonCard** [comment]
@Ukkoo @adegeo Thank you for your feedback and letting me know. I'll uplift this article to human translation.

**Comment by Ukkoo** [comment]
@adegeo <https://github.com/adegeo> @JasonCard
<https://github.com/JasonCard>
Thank you!
Perhaps the translation is not quite as bad as I wrote after all, but
since the content is somewhat complex, it is easy to get confused by the
inaccurate translation and the misplacement of the linked keywords.

Am 12.04.2021 um 22:12 schrieb Jason Card:

**Comment by JasonCard** [comment]
@Ukkoo Thank you again for your feedback. This article has now been human translated, but please let us know if you still find any inaccurate translation. 
cc @adegeo

**Comment by Ukkoo** [comment]
Much better, thank you!

**Comment by adegeo** [comment]
@JasonCard just FYI on the comment left. I know you guys are working on some translation updates so I want to make sure you see this.

**Comment by JasonCard** [comment]
@adegeo Thank you, I didn't realize there was additional feedback after the first line :)
@Ukkoo Thank you for the additional feedback on systematic error for machine translated content in German. I've passed on this feedback and hope they can address this issue in the machine translation engine.
